In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.1.0'

### Constantes

In [5]:
# Definir una constante en TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [4]:
# Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

In [6]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy
tensor_20.numpy()

array([[23,  4],
       [32, 51]])

In [7]:
# Podemos convertir un array de numpy a un tensor de tf directamente
num_tensor = np.array([[23,4],[21,56]])
tensor_from_np = tf.constant(num_tensor)
tensor_from_np

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [21, 56]])>

### Variables

In [10]:
# Array bidimensional en filas y columnas
var = tf.Variable([[2.,7.09],[4.55,1.09]])
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2.  , 7.09],
       [4.55, 1.09]], dtype=float32)>

In [11]:
var.numpy()

array([[2.  , 7.09],
       [4.55, 1.09]], dtype=float32)

In [15]:
# cambiar un valor especifico de una variable
# Cambiar fila 0, columna 2 el valor 100
var[0,1].assign(100)
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[  2.  , 100.  ],
       [  4.55,   1.09]], dtype=float32)>

### Operaciones con tensores

In [18]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [24]:
# sumandole un escalar a un tensor suma a cada celda del tensor
tensor = tensor + 2
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [27]:
# multiplicar un escalar por un tensor
tensor = tensor * 5
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 30],
       [35, 40]])>

In [28]:
# Obtener los cuadrados de todos los números de un tensor en tf
np.square(tensor)

array([[ 625,  900],
       [1225, 1600]], dtype=int32)

In [29]:
# Obtener la raíz cuadrada de todos los números de un tensor
np.sqrt(tensor)

array([[5.        , 5.47722558],
       [5.91607978, 6.32455532]])

### Producto escalar entre dos tensores

In [32]:
# dot() Producto de puntos de dos matrices. Específicamente,
np.dot(tensor, tensor_20)

array([[1535, 1630],
       [2085, 2180]])

### Strings 

In [33]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

In [34]:
# longitud de un string en tf
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [35]:
# Transforma en formato de texto a la UTF8
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119])>

In [38]:
# Array de cadenas 
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

for i in tf_string_array:
    print(i)
    

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
